### ISSUE TITLE
Including 2 (both) AWS conditions in a redirect. 

### ISSUE THREAD

**Issue by dirkcuys** [laurilehmijoki/configure-s3-website#20]
I'm trying setup a redirect that only redirects a given prefix if it doesn't exist on the site:

```
  - condition:
      key_prefix_equals: en/courses/
      http_error_code_returned_equals: 404
    redirect:
      host_name: courses.p2pu.org
      protocol: https
      http_redirect_code: 301
```
But this doesn't work when I run s3_website push.
